## This source code is DualSDF
##   (https://github.com/zekunhao1995/DualSDF)
## Copyright (c) 2020 Zekun Hao
## This source code is licensed under the MIT license found in the
## 3rd-party-licenses.txt file in the root directory of this source tree.

all:
	python setup.py build_ext --inplace

clean:
	rm -rf *.o *.a *.so test build
